// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM9YoDV_MI8m5oLNJxOF73EYjgI8JBGfA',
    appId: '1:586812781520:web:8296efdbb990e93a283fd5',
    messagingSenderId: '586812781520',
    projectId: 'incipiens-1ce79',
    authDomain: 'incipiens-1ce79.firebaseapp.com',
    storageBucket: 'incipiens-1ce79.appspot.com',
    measurementId: 'G-7PQ8C9PD15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkghtMyCAVRa6zbJ2o6i46RngmgSxcz3U',
    appId: '1:586812781520:android:f8b622c6feffb69c283fd5',
    messagingSenderId: '586812781520',
    projectId: 'incipiens-1ce79',
    storageBucket: 'incipiens-1ce79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCramlvbW6N8aXvcOY7ZNhao_A8bgGTJ3I',
    appId: '1:586812781520:ios:e250b91dd3a43840283fd5',
    messagingSenderId: '586812781520',
    projectId: 'incipiens-1ce79',
    storageBucket: 'incipiens-1ce79.appspot.com',
    iosClientId: '586812781520-vodsjqk72c3d4m6mnb2bjlv4ek7243sv.apps.googleusercontent.com',
    iosBundleId: 'com.incipiens.userapp',
  );
}
